### PR TITLE
MAINT: instrument tests update

### PR DESCRIPTION
**Pull request by aburrell**
Updates syntax for instrument tests inherited from pysat as part of pysat/pysat#552.

- End-to-end instrument tests now iterate over a list of dict objects containing info to create an instrument
- `pytest.mark` statements updated accordingly
- `package` renamed as `inst_loc`
- Currently failing on Travis since these updates are not in pysat develop-3, but passes locally when using the `tst/inst_test_class_update` branch of pysat.

### CODE REVIEW

**Comment by jklenzing** [comment]
Re-ran the travis tests since changes have been merged at pysat.

**Comment by jklenzing** [comment]
This one should be updated with `tempfile` compatibility too. 
https://github.com/pysat/pysatNASA/blob/14d77d4104a71f750ce20c785b7838adc6294427/pysatNASA/tests/test_instruments.py#L42-L66

**Review by jklenzing — APPROVED** [review]
Looks good.  Push tests fail due to problems solved in the main branch.  Pull tests are doing fine.

**Comment by aburrell** [comment]
Thanks Jeff!  Merging.

**Pull request merged**
