### PR TITLE
MAINT: remove unused kwarg

### PR DESCRIPTION
**Pull request by aburrell**
Removed unused kwarg `fake_daily_files_from_monthly` from `list_files` routine in all instruments.

### CODE REVIEW

**Comment by jklenzing** [comment]
According to coveralls, `methods.filter_data_single_date` has gone from covered to uncovered.  Not sure why this is the case.

https://coveralls.io/builds/35740294/source?filename=pysatMadrigal%2Finstruments%2Fmethods%2Fmadrigal.py

**Comment by rstoneback** [comment]
jro_isr preprocess method still labeled default.

**Comment by rstoneback** [comment]
> jro_isr preprocess method still labeled default.

I can't make a suggestion for a line that hasn't changed so I pushed a tiny commit to change the name.

**Comment by rstoneback** [comment]
> > jro_isr preprocess method still labeled default.
> 
> I can't make a suggestion for a line that hasn't changed so I pushed a tiny commit to change the name.

Since I made a push its also on me that it broke.
Current error is with download. I don't think that actually has anything to do with my change so tests are restarting.

**Comment by rstoneback** [comment]
> > > jro_isr preprocess method still labeled default.
> > 
> > 
> > I can't make a suggestion for a line that hasn't changed so I pushed a tiny commit to change the name.
> 
> Since I made a push its also on me that it broke.
> Current error is with download. I don't think that actually has anything to do with my change so tests are restarting.

Test failures are driven by the changes in meta labels, with the updates in #28.

**Review by rstoneback — APPROVED** [review]
Thanks @aburrell!

**Pull request merged**
